server:
  port: 8080
  address: 0.0.0.0

test:
  dummy: "확인용"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cakedaY_db?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: rlarkdtks94302.


  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: "1943daef8105c08a829f84c985ababd2"
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname, profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

file:
  upload-dir: C:\Users\San\Desktop\cakedaY-backend-main\images

app:
  base-url: http://192.168.0.4:8080

fastapi:
  url: http://localhost:8000/recommend



logging:
  level:
    org.hibernate.SQL: debug
